extends:
    - "eslint:recommended"
    - "google"
rules:
    no-console: 0
    typescript/no-unused-vars: 1
    no-undef: 0
    # Additional, per-project rules...
env:
    node: true
    mocha: true
    es6: true
parser: typescript-eslint-parser
parserOptions:
    sourceType: module
    ecmaFeatures:
        modules: true
plugins:
    - "typescript"
