extends:
    - "eslint:recommended"
    - "google"
rules:
    no-console: 0
    # Additional, per-project rules...
env:
    node: true
    mocha: true
    es6: true
parser: typescript-eslint-parser
parserOptions:
    sourceType: module
    ecmaFeatures:
        modules: true
